### ISSUE TITLE
Add a tilde to the thread name avoiding test failures in other libraries

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Analytics#11]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Analytics-2.20.4](https://github.com/OpenHFT/Chronicle-Analytics/releases/chronicle-analytics-2.20.4), [BOM-2.20.192](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.192)
