### ISSUE TITLE
Add provisions to protect form a large number of instances started simultaneously

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Analytics#14]
This might be in the form of touching a temporary/hidden file and making sure there is a grace period between processes sending data

**Comment by hft-team-city** [comment]
Released in [Chronicle-Analytics-2.23ea0](https://github.com/OpenHFT/Chronicle-Analytics/releases/chronicle-analytics-2.23ea0), [BOM-2.23ea16](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea16)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Analytics-2.23ea0](https://github.com/OpenHFT/Chronicle-Analytics/releases/chronicle-analytics-2.23ea0), [BOM-2.23ea17](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea17)
