### ISSUE TITLE
Add a NOOP module with pom.xml to produce the NOOP jar

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Analytics#7]

**Comment by RobAustin** [comment]
this is done its https://repo1.maven.org/maven2/net/openhft/chronicle-analytics/0.EMPTY/

**Comment by hft-team-city** [comment]
Released in [Chronicle-Analytics-2.20.2](https://github.com/OpenHFT/Chronicle-Analytics/releases/chronicle-analytics-2.20.2), [BOM-2.20.171](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.171)
