### ISSUE TITLE
Add filtering for a certain amount of messages per time unit

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Analytics#8]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Analytics-2.20.2](https://github.com/OpenHFT/Chronicle-Analytics/releases/chronicle-analytics-2.20.2), [BOM-2.20.171](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.171)
