### ISSUE TITLE
Reduce connection time-out to 2 seconds

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Analytics#9]
Since the analytics feature is non-critical to the library using it, it makes sense to give up early, should there be a network latency problem. This prevents lingering jobs to pile up.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Analytics-2.20.4](https://github.com/OpenHFT/Chronicle-Analytics/releases/chronicle-analytics-2.20.4), [BOM-2.20.192](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.192)
